### ISSUE TITLE
Enclosure not found on TinkerFiles

### ISSUE THREAD

**Issue by TopBanana123** [OpenGarage/OpenGarage-Hardware#10]
I have an issue with the OpenGarage enclosure in that it does not accept a standard USB cable because the USB Port is too recessed 

I made the hole bigger and in the process cracked the case, and would like to print another. The GitHub page does to search for OpenGarage on TinkerHub, however I get no results

![image](https://github.com/OpenGarage/OpenGarage-Hardware/assets/43852644/06c15cdc-8e86-4c40-9858-d357ba446576)

Is there an STL file I could get to print another?

**Comment by HoECoder** [comment]
I found them here:
https://www.tinkercad.com/things/fSLeOxNVjwK-opengarage-enclosure

And here:
https://www.tinkercad.com/things/2qRHEHzTHSL-opengarage-enclosure-v2

Depending on your HW Version

**Comment by rayshobby** [comment]
The 3D model in STL format is available in the Enclosure folder:
https://github.com/OpenGarage/OpenGarage-Hardware/tree/master/Enclosure

**Comment by TopBanana123** [comment]
Perfect, thanks guys! Would be nice if the main page linked to the STL instead of asking you to search
