### ISSUE TITLE
Value of R9

### ISSUE THREAD

**Issue by terrag42** [OpenGarage/OpenGarage-Hardware#2]
I noticed that in your schematic and in the BOM, R9 is specified as 10k Ohms. If I'm using a normal LED whose rated voltage is about 3.2V, I don't think it will be very bright, is this what you have found? Since the LED's voltage is coming from the ESP8266 (3.3 V), would it be OK for me to change the value of R9 to something like 220 ohms or even 47 ohms?

**Comment by rayshobby** [comment]
Sorry, that's a typo. It should be something small (like 220ohm or 330ohm).
