### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by ragenhe** [OpenGarage/OpenGarage-Hardware#3]
Is MQTT a more stable env than just relying on wifi interaction.

My unit sometimes appears disconnected from wifi, and the state isn't updated in home assistant.

If I setup for MQTT integration, I feel that data movement might will be more stable.

Are there any steps / details document on MQTT setup?

**Comment by rayshobby** [comment]
This issue should be posted to OpenGarage-Firmware repo, not here (this is Hardware repo).
