### ISSUE TITLE
Version 1.4 Open Source Hardware Version?

### ISSUE THREAD

**Issue by wiesl** [OpenGarage/OpenGarage-Hardware#5]
Hello,

Ordered 2x OpenGarage Hardware. Unfortunately this is Version V1.4 of OpenGarage Hardware.

Where can I find V1.4 of the Schematic and PCB Eagle files?

Thnx.

**Comment by rayshobby** [comment]
I've just checked it in.

**Comment by wiesl** [comment]
Thnx.
