### ISSUE TITLE
missing part? buzzer not working

### ISSUE THREAD

**Issue by ghost** [OpenGarage/OpenGarage-Hardware#7]
Hello. i just assembled one Opengarage 2.0 but the buzzer is not working. how can i trouble shoot? this is my board. did i missed some parts except the ultra sonic sensor?

![IMG20221029140034](https://user-images.githubusercontent.com/35889916/198837339-e4b9ddca-b33c-4b8d-95e5-b59f3d2dfcbe.jpg)

**Comment by rayshobby** [comment]
Q1 (MMBT3904) on your board is missing.
