### ISSUE TITLE
Possible to use with LA400 Gate Opener?

### ISSUE THREAD

**Issue by TopBanana123** [OpenGarage/OpenGarage-Hardware#9]
I'm wondering if its possible to connect this up to an LA400 gate opener? Its a fairly recent model and also apparently has single button control on the circuit board

**Comment by rayshobby** [comment]
If directly wiring OpenGarage to your door's button terminals doesn't work, then as long as you have a working button/remote, you can always solder two wires to the button/remote, and wire them to OpenGarage. That should always work.
